[package]
name = "suricatax-rule-parser"
version = "0.2.0-alpha.1"
authors = ["Jason Ish <jason@codemonkey.net>"]
edition = "2021"
rust-version = "1.63.0"
description = "A parser for Suricata rules"
repository = "https://github.com/jasonish/suricatax-rule-parser-rs"

[workspace]
members = [".", "rulejs", "fuzz"]

[dependencies]
lazy_static = "1.4.0"
nom = "7.1.3"
num-traits = "0.2.18"
serde = { version = "1.0.199", default-features = false, features = ["std", "derive"] }
serde_json = "1.0.116"
