[package]
name = "rjs"
version = "0.1.0"
edition = "2021"
authors = ["Jason Ish <jason@codemonkey.net>"]

[dependencies]
suricatax-rule-parser = { path = ".." }
clap = { version = "3.2.23", features = ["derive"] }
serde = "1.0.163"
serde_yaml = "0.9.21"
serde_json = "1.0.96"
